import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import TopNav from "@/components/TopNav";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "TK Al Ishlah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-halfterm antialiased w-screen overflow-x-hidden"
      >
        <TopNav />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
